### PR TITLE
rperform test

### PR DESCRIPTION
**Pull request by tdhock**
hi @EngineerDanny I have attempted to setup Rperform in this repo. Do you think it looks correct?
I expected there should be some easy way to run timings on all commits in any PR. But I observed that in plot_branchmetrics example code that there are specifically named branches, 
```r
## TEST 5
#  Rperform::plot_branchmetrics(
#    test_path = "inst/tests/test-check.r",
#    metric = "time",
#    branch1 = "rperform_test",
#    branch2 = "master",
#    save_data = T,
#    save_plots = F
# )
```
can branch1 default to the current PR compare branch, and branch2 default to the PR base branch?

### CODE REVIEW

**Comment by EngineerDanny** [comment]
@tdhock Sure. I will use the main branch and the PR branches for `branch2` and `branch1` respectively. 
I can maintain the parameters to give control to the user.

**Comment by tdhock** [comment]
build failures seem to be because no pdflatex, try to fix by installing tinytex before check, https://github.com/r-lib/actions/issues/138

**Comment by EngineerDanny** [comment]
> build failures seem to be because no pdflatex, try to fix by installing tinytex before check, [r-lib/actions#138](https://github.com/r-lib/actions/issues/138)

@tdhock  Please do you mean the recent `Rperform` build failures? Or the `PeakSegDisk` build failures? Could you explain?

**Comment by tdhock** [comment]
hi @EngineerDanny sorry for the confusion. the previous comment was to myself, about the R-CMD-check build (not rperform), so please ignore. I'm trying to get R-CMD-check to work by installing pdflatex and tex packages as in https://community.rstudio.com/t/add-latex-tinytex-dependencies-to-github-actions/90896/2

However @EngineerDanny can you please help by investigating why Rperform is not making a PR comment here? it looks like the rperform build is being run with success but no PR comment is being made.

**Comment by tdhock** [comment]
hi @EngineerDanny can you please help by investigating why Rperform is not making a PR comment here? it looks like there are two rperform builds, https://github.com/tdhock/PeakSegDisk/tree/rperform/.github/workflows
one succeeds, the other fails. is that normal/expected?

**Comment by tdhock** [comment]
@EngineerDanny I get some installation error, can you please investigate and recommend a fix?
```

2022-08-24T21:05:47.5902453Z ✔ Installed textshaping 0.3.6  (50ms)
2022-08-24T21:05:47.6022704Z ℹ Building ragg 1.2.2
2022-08-24T21:06:13.0171971Z ✔ Built httpuv 1.6.5 (2m 5s)
2022-08-24T21:06:13.2246125Z ✔ Installed httpuv 1.6.5  (168ms)
2022-08-24T21:06:13.2714809Z ✔ Installed tinytex 0.41  (22ms)
2022-08-24T21:06:13.2835644Z ℹ Building rmarkdown 2.15
2022-08-24T21:06:13.5868361Z 
2022-08-24T21:06:13.5886827Z ##[error]Error: <callr_remote_error: `path` must exist>
2022-08-24T21:06:13.5889108Z  in process 8277 
2022-08-24T21:06:13.5889582Z -->
2022-08-24T21:06:13.5889890Z <simpleError: `path` must exist>
2022-08-24T21:06:13.5893842Z 
2022-08-24T21:06:13.5893978Z  Stack trace:
2022-08-24T21:06:13.5894128Z 
2022-08-24T21:06:13.5894277Z  12. (function (...)  ...
2022-08-24T21:06:13.5894714Z  13. base:::withCallingHandlers(cli_message = function(msg) { ...
2022-08-24T21:06:13.5895396Z  14. get("lockfile_install_internal", asNamespace("pak"))(...)
2022-08-24T21:06:13.5895761Z  15. plan$install()
2022-08-24T21:06:13.5896197Z  16. pkgdepends:::install_package_plan(plan, lib = private$library,  ...
2022-08-24T21:06:13.5896632Z  17. base:::withCallingHandlers({ ...
2022-08-24T21:06:13.5897010Z  18. pkgdepends:::start_task(state, task)
2022-08-24T21:06:13.5897407Z  19. pkgdepends:::start_task_build(state, task)
2022-08-24T21:06:13.5897882Z  20. pkgdepends:::make_build_process(path, pkg, tmp_dir, lib, vignettes,  ...
2022-08-24T21:06:13.5898434Z  21. withr::with_libpaths(c(tmplib, lib), action = "prefix", pkgbuild_process$ne ...
2022-08-24T21:06:13.5899080Z  22. base:::force(code)
2022-08-24T21:06:13.5899533Z  23. pkgbuild_process$new(path, tmp_dir, binary = binary, vignettes = vignettes, ...
2022-08-24T21:06:13.5899947Z  24. pkgbuild:::initialize(...)
2022-08-24T21:06:13.5900409Z  25. pkgbuild:::rcb_init(self, private, super, path, dest_path, binary,  ...
2022-08-24T21:06:13.5900941Z  26. pkgbuild:::build_setup(path, dest_path, binary, vignettes, manual,  ...
2022-08-24T21:06:13.5901382Z  27. base:::stop("`path` must exist", call. = FALSE)
2022-08-24T21:06:13.5901788Z  28. base:::.handleSimpleError(function (e)  ...
2022-08-24T21:06:13.5902147Z  29. h(simpleError(msg, call))
2022-08-24T21:06:13.5902423Z  30. base:::stop(e)
2022-08-24T21:06:13.5902698Z  31. (function (e)  ...
2022-08-24T21:06:13.5902850Z 
2022-08-24T21:06:13.5902988Z  x `path` must exist 
2022-08-24T21:06:13.5903139Z 
2022-08-24T21:06:13.5903458Z Execution halted
2022-08-24T21:06:13.6113779Z ##[error]Process completed with exit code 1.
2022-08-24T21:06:13.6205732Z ##[warning]Unexpected input(s) 'benchmarking_repo', 'benchmarking_ref', 'benchmarking_path', valid inputs are ['cache-version', 'rperform_ref']
2022-08-24T21:06:13.6210215Z Post job cleanup.
2022-08-24T21:06:13.6258664Z Post job cleanup.
2022-08-24T21:06:13.6293710Z Post job cleanup.
2022-08-24T21:06:13.7510040Z [command]/usr/bin/git version
2022-08-24T21:06:13.7560383Z git version 2.37.2
2022-08-24T21:06:13.7604994Z Copying '/home/runner/.gitconfig' to '/home/runner/work/_temp/8fe6bade-607d-4f25-b059-4c7a95a320c2/.gitconfig'
2022-08-24T21:06:13.7618740Z Temporarily overriding HOME='/home/runner/work/_temp/8fe6bade-607d-4f25-b059-4c7a95a320c2' before making global git config changes
2022-08-24T21:06:13.7621585Z Adding repository directory to the temporary git global config as a safe directory
2022-08-24T21:06:13.7628800Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/PeakSegDisk/PeakSegDisk
2022-08-24T21:06:13.7670869Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-08-24T21:06:13.7707833Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-08-24T21:06:13.7998662Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-08-24T21:06:13.8025255Z http.https://github.com/.extraheader
2022-08-24T21:06:13.8044781Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2022-08-24T21:06:13.8089978Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-08-24T21:06:13.8545793Z Cleaning up orphan processes
```

**Comment by EngineerDanny** [comment]
@tdhock Sure. I am looking into it. I will update you soon

**Pull request closed without merging**
